#!/bin/bash
## Terraria service script

## Vars
DEBUGGING=true
WRITE_DIR=/opt/terraria-service
PIDFILE="${WRITE_DIR}/server.pid"
CURRENT_USER=`whoami`
USERNAME=server #temporary


## Debugger
debug()
{
	echo "Debugger"
	echo -e "USERNAME:\t${USERNAME}"
	echo -e "CURRENT_USER:\t${CURRENT_USER}"
	echo -e "WRITE_DIR:\t${WRITE_DIR}"
	echo -e "PIDFILE:\t${PIDFILE}"
	echo
}
if $DEBUGGING; then
	debug
fi


## Usage display
usage()
{
	echo "Usage: $0 <COMMAND>"
	echo
	echo "Commands:"
	echo -e "  start\t\t Starts the server"
	echo -e "  stop\t\t Stops the server"
	echo -e "  help\t\t Show this help message"
}


# Execute for User
## Helper function
## Executes the provided command
exec_user()
{
	if [ $CURRENT_USER == $USERNAME ]; then 		# Are you the terraria user?
		echo "Executing ${1}"
		bash -c "$1"
	elif [ "$(id -u)" == "0" ]; then			# Are you root?
		echo "Please do not run this as root!"
	else							# You are neither
		echo "Run this script as the $USERNAME user!"
		exit 1
	fi
}


# Start script
## Creates a new PID file
start()
{
	if exec_user "touch ${PIDFILE}" ; then
		echo "Success?"
		exit 1;
	fi

	echo "fail?"
	exit 1
}


## Routing
case "$1" in
	start)
		start
		;;
	stop)
		echo "Stopping the server.."
		echo "Could not stop the server (code not implemented)"
		;;
	help|--help|-h)
		usage
		;;
	*)
		echo "Unknown command"
		usage
		exit 1
		;;
esac

exit 0
